### ISSUE TITLE
Some string not translated/filtered

### ISSUE THREAD

**Issue by piffpaffpuff** [franticpsyx/woocommerce-qtml#6]
WP 3.8.4, WC 2.2.7, QTML 2.0.11

- the product category description isn't translated in the frontend when you use qtranslate [:lang] tags in the description text. ie: it shows "[:de]Kategorietext[:en]Category text" instead of "Kategorietext"

- titles for product attributes are not translated when displayed on the admin order details screen. ie: it shows "[:de]Grösse[:en]Size" instead of "Grösse"

**Comment by franticpsyx** [comment]
>the product category description isn't translated in the frontend when you use qtranslate [:lang] tags in the description text. ie: it shows "[:de]Kategorietext[:en]Category text" instead of "Kategorietext"

Should be fixed in 2.0.12.

>titles for product attributes are not translated when displayed on the admin order details screen. ie: it shows "[:de]Grösse[:en]Size" instead of "Grösse"

Don't know if there's a filter there - but if there is, please feel free to let me know or send a pull request!
