### ISSUE TITLE
wc_qtml_plugins_init runs to early

### ISSUE THREAD

**Issue by piffpaffpuff** [franticpsyx/woocommerce-qtml#7]
i would like to use one of the hooks that is used in the `wc_qtml_plugins_init` function. but the `plugins_loaded` hook that calls this function is called by wordpress before any theme function is called. this means the hooks inside `wc_qtml_plugins_init` can't be called via the `functions.php`. this isn't that useful.

could you call this function ie. with `after_setup_theme`?

https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L237

**Comment by franticpsyx** [comment]
There is only one filter there for hiding the admin menu settings of qT. I don't quite get why that has anything to do with your theme.

**Comment by piffpaffpuff** [comment]
Where else would you put in the Code for that filter than in the functions.php?
