### ISSUE TITLE
qTranslate-X compatibility

### ISSUE THREAD

**Issue by piffpaffpuff** [franticpsyx/woocommerce-qtml#8]

**Comment by franticpsyx** [comment]
Pull request please :)

**Comment by piffpaffpuff** [comment]
Sorry, I do not know your Plugin-Code. But it looks like you do, or aren't your the Dev?

**Comment by franticpsyx** [comment]
Doesn't qTranslate-X provide a plugin for WC compatibility?

WC-qTML was originally create for qTranslated and later on tweaked to work with mqTranslate. It looks like both of them are now EOL.

If qTranslate-X authors are releasing their own plugin for WooCommerce compatibility, this probably has no reason to include qTranslate-X support.
